# Generated by Django 4.2.4 on 2023-08-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=10)),
                ('created', models.DateTimeField()),
                ('completed', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='needs_CMM',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
