# Generated by Django 4.2.4 on 2023-08-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_completejob_job_needs_cmm_alter_job_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
