# Generated by Django 4.2.4 on 2023-08-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='completejob',
            name='delta',
            field=models.FloatField(default=0),
        ),
    ]
